server:
  port: 9999
  servlet:
    context-path: /cloud-alibaba-order

spring:
  datasource:
    url: jdbc:h2:D:/Users/100451/IdeaProjects/spring-boot-demo/cloud_alibaba
    driver-class-name: org.h2.Driver
    username: sa
    password:
      