-- C_PS_E_ARCHIVE definition

CREATE TABLE C_PS_E_ARCHIVE
(
    ID                   varchar(100) PRIMARY KEY NOT NULL,
    EINVOICENUMBER       varchar(100)             NOT NULL,
    EINVOICECODE         varchar(100)             NOT NULL,
    RANDOMNUMBER         varchar(50),
    ISSUEDATE            varchar(20),
    TOTALAMOUNT          NUMBER(20,2),
    REMARK               varchar(500),
    USERID               varchar(50),
    ARCHIVEDATE          DATE,
    EINVOICENAME         varchar(100),
    PAYERPARTYNAME       varchar(300),
    INVOICINGPARTYNAME   varchar(500),
    EINVOICETYPE         varchar(2),
    CHANNELINFO          varchar(500),
    ARCHIVEWAY           varchar(30),
    ARCHIVECHANNEL       varchar(10),
    ARCHIVECHANNELVALUE  varchar(100),
    AGENCYID             varchar(32),
    HOSPITALBUSINESSTYPE varchar(2),
    UPDATEDATE           DATE,
    PAYDATE              DATE,
    OTHER_NO             varchar(50),
    ADMISSION_DATE       varchar(20),
    DISCHARGE_DATE       varchar(20),
    INVOICE_ASSORT       varchar(10),
    BLOCK_HASH           varchar(256),
    INVOICE_STATUS       varchar(8)
);

COMMENT
ON TABLE C_PS_E_ARCHIVE IS ''财税票归集表'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.ID IS ''主键ID'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.EINVOICENUMBER IS ''票据号码'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.EINVOICECODE IS ''票据代码'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.RANDOMNUMBER IS ''校验码'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.ISSUEDATE IS ''日期'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.TOTALAMOUNT IS ''金额'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.REMARK IS ''说明'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.USERID IS ''用户ID'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.ARCHIVEDATE IS ''归档时间'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.EINVOICENAME IS ''票据名称'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.PAYERPARTYNAME IS ''缴款人'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.INVOICINGPARTYNAME IS ''开票单位'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.EINVOICETYPE IS ''票据类型'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.ARCHIVEWAY IS ''归集方式'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.ARCHIVECHANNEL IS ''归集渠道'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.ARCHIVECHANNELVALUE IS ''归集渠道值'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.AGENCYID IS ''单位识别码'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.UPDATEDATE IS ''更新时间'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.OTHER_NO IS ''其他系统的业务号:当前有专利局网站id'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.BLOCK_HASH IS ''区块链hash'';
COMMENT
ON COLUMN C_PS_E_ARCHIVE.INVOICE_STATUS IS ''票据状态'';