server:
  port: 9999
  servlet:
    context-path: /springbootdemo
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048
 
spring:
  application:
    name: springbootdemo
  http:
    log-request-details: true
    
    
#文件存储
nontax3:
  vfs:
    baseFolder:
    mode: minio
    minio:
      bucketName: pjcloud-10002
      region: http://192.168.1.225:9000
      secretKey: minioadmin
      accessKey: minioadmin
