server:
  port: 9999
  servlet:
    context-path: /springbootdemo
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048
 
spring:
  application:
    name: springbootdemo
  http:
    log-request-details: true
  dubbo:
    registry: zookeeper://192.168.1.250:2181
    server: true
    protocol:
      port: 28888
# 数据库
  datasource:
    name: oracle
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.2.20:1521:orcl
    username: OPERATION_CENTER
    password: OPERATION_CENTER


#文件存储
nontax3:
  vfs:
    baseFolder:
    mode: minio
    minio:
      bucketName: pjcloud-10002
      region: http://192.168.1.225:9000
      secretKey: minioadmin
      accessKey: minioadmin
