server:
  port: 9999
  servlet:
    context-path: /springbootdemo
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

spring:
  application:
    name: springbootdemo
  http:
    log-request-details: true
  dubbo:
    registry: zookeeper://192.168.1.250:2181
    server: true
    protocol:
      port: 28888
  # 数据库
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      operation:
        url: jdbc:oracle:thin:@192.168.2.20:1521/orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: OPERATION_CENTER
        password: OPERATION_CENTER
        max-open-prepared-statements: 100
        filters: stat,slf4j #监控统计的stat,以及防sql注入的wall
      core:
        url: jdbc:oracle:thin:@192.168.2.20:1521/orcl
        driver-class-name: oracle.jdbc.driver.OracleDriver
        username: PC_CORE01
        password: PC_CORE01

# mybatis-plus的配置
mybatis-plus:
  global-config:
    banner: false
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true
  configuration:
    # 输出到控制台
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 输出到日志文件中 配置slf4j或者log4j2都行org.apache.ibatis.logging.log4j2.Log4j2Impl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 禁止日志输出
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    jdbc-type-for-null: 'null'
  mapper-locations: classpath*:mapper/*/${spring.datasource.name}/*Mapper.xml

#文件存储
nontax3:
  vfs:
    baseFolder:
    mode: minio
    minio:
      bucketName: pjcloud-10002
      region: http://192.168.1.225:9000
      secretKey: minioadmin
      accessKey: minioadmin
